services:    
  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8098:8080"
    volumes:
      - ./target/my-spring-app.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: spring-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: its      
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql  # C:/db-data 폴더를 /var/lib/mysql에 연결
      - ./its.sql:/docker-entrypoint-initdb.d/its.sql  # 덤프파일 자동 실행
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

volumes:
  db-data:
